### ISSUE TITLE
🛣 Road to `1.0.0`

### ISSUE THREAD

**Issue by dtetto** [bustle/mobiledoc-vdom-renderer#1]
* [x] Export Typescript definition files
* [x] Build `ESNext`-targeted version (`.mjs`) for package “module” field
* [x] Don’t run `upgradeMobiledoc` by default (instead, throw on unmatched versions)
* [x] License (MIT, copyright Bustle)
* [x] Rename `mobiledoc-vdom-renderer`
* [x] Release as open source on Github
* [x] CI & badge
* [x] `npm publish` publicly as `mobiledoc-vdom-renderer`
* [x] Code of Conduct (#4)

**Comment by gpoitch** [comment]
These are all done now
