### ISSUE TITLE
Example needed for using `getCardComponent` with react

### ISSUE THREAD

**Issue by dbchristopher** [bustle/mobiledoc-vdom-renderer#15]
I'm currently unable to get `mobiledoc-vdom-renderer` to work when passing in a react component as a card. If I could see a basic example of what the renderer is expecting I think I'd be unblocked very quickly. Thank you!

**Comment by cainlevy** [comment]
Here's how I have it working currently. Note that this is a mix of React and TypeScript:

```tsx
enum CARDS {
  video = 'video',
  image = 'image',
}

type ComponentGetter = (props: {payload: any}) => React.ReactNode;

const cards: {[key in CARDS]: ComponentGetter} = {
  [CARDS.video]: ({payload}) => <Video playlistUrl={payload.encodings[0]} poster={payload.poster} />,
  [CARDS.image]: ({payload}) => <Image path={payload.path} />,
};

const render = Renderer({
  createElement: React.createElement,
  getCardComponent: (type) => cards[type],
});
```

The `Video` and `Image` card components are completely standard.

**Comment by dbchristopher** [comment]
Very much appreciated @cainlevy! That was super helpful.
