### ISSUE TITLE
Webpack imports: package's "module" target should be mostly ES5

### ISSUE THREAD

**Issue by cainlevy** [bustle/mobiledoc-vdom-renderer#9]
I believe the convention for the "module" target in the package.json is ES5 with ES2015 imports. Currently the `tsconfig.module.json` config is outputting ES2015 syntax _and_ modules.

This breaks imports in Webpack:

```
ERROR in ./node_modules/mobiledoc-vdom-renderer/dist/index.mjs
8:412-422 Can't import the named export 'throwError' from non EcmaScript module (only default export is available)
 @ ./node_modules/mobiledoc-vdom-renderer/dist/index.mjs
 @ ./src/lib/document.tsx
 @ ./src/components/routes/Home.tsx
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.tsx
```

**Comment by cainlevy** [comment]
I tried fiddling with `tsconfig.module.json` and installing the result with `npm pack`, then discovered that the problem goes a bit deeper: when `index.mjs` imports another file, it resolves to the commonjs `.js` version.

Possible solutions:

* use rollup or similar so the main target is a self-contained single file and any module lookups only find module targets
* create different `dist` directories for main & module

**Comment by dtetto** [comment]
Thanks for the dig, both solutions make sense to me.

I’ll have to look into this, quite bit of cargo-culting going on with my setup here! 😬

**Comment by cainlevy** [comment]
Works for me! 👍 

For what it's worth, I tried compiling all three targets (ES5, ES2015, ES2017) into three different directories and comparing them with `diff -r a/ b/`. There's no difference between ES2015 and ES2017 for this library, but there is a fair difference between ES5 and ES2015.

This may only present issues for someone who is a) using package.module and b) unable to handle ES2015 source. I have no idea what build pipeline that describes.
